# Generated by Django 5.2.10 on 2026-02-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_crossreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="law",
            name="last_verified",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this law's source was verified as still available",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="law",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="URL where this law was obtained",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="law",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="State name (e.g., 'Jalisco', 'Ciudad de México')",
                max_length=100,
                null=True,
            ),
        ),
    ]
