# Generated by Django 5.2.10 on 2026-02-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_law_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="law",
            name="law_type",
            field=models.CharField(
                choices=[
                    ("legislative", "Legislative"),
                    ("non_legislative", "Non-Legislative"),
                ],
                db_index=True,
                default="legislative",
                help_text="Legislative (from Congress) or Non-Legislative (executive, judicial, autonomous)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="law",
            name="tier",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
