# Generated by Django 5.2.10 on 2026-02-07 20:10

from django.db import migrations


def backfill_law_type(apps, schema_editor):
    """Mark laws whose official_id contains '_nl_' as non-legislative."""
    Law = apps.get_model("api", "Law")
    updated = Law.objects.filter(official_id__contains="_nl_").update(
        law_type="non_legislative"
    )
    if updated:
        print(f"\n  Backfilled {updated} non-legislative laws")


def reverse_backfill(apps, schema_editor):
    """Reset all law_type back to legislative."""
    Law = apps.get_model("api", "Law")
    Law.objects.filter(law_type="non_legislative").update(law_type="legislative")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_law_type_field"),
    ]

    operations = [
        migrations.RunPython(backfill_law_type, reverse_backfill),
    ]
