# Generated by Django 5.2.10 on 2026-02-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_increase_official_id_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportlog",
            name="law_id",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="law",
            name="category",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="law",
            name="state",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="State name (e.g., 'Jalisco', 'Ciudad de México')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lawversion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
