# Generated by Django 5.2.10 on 2026-02-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_webhooksubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=500)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("result_count", models.IntegerField(default=0)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hashed IP for session grouping",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="apikey",
            new_name="api_apikey_prefix_3fde9a_idx",
            old_name="api_apikey_prefix_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="apiusagelog",
            new_name="api_apiusag_api_key_896fb7_idx",
            old_name="api_apiusagelog_prefix_created_idx",
        ),
        migrations.RenameIndex(
            model_name="apiusagelog",
            new_name="api_apiusag_ip_addr_19e9d4_idx",
            old_name="api_apiusagelog_ip_created_idx",
        ),
        migrations.RenameIndex(
            model_name="webhooksubscription",
            new_name="api_webhook_api_key_78ae77_idx",
            old_name="api_webhook_key_active_idx",
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["query", "created_at"], name="api_searchq_query_590f3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["result_count", "created_at"],
                name="api_searchq_result__934c3f_idx",
            ),
        ),
    ]
