# Generated by Django 5.2.10 on 2026-02-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_search_query_analytics"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "janua_user_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "topics",
                    models.JSONField(
                        default=list,
                        help_text="e.g. ['federal', 'fiscal', 'weekly_digest']",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email", "is_active"],
                        name="api_newslet_email_690b0f_idx",
                    )
                ],
            },
        ),
    ]
