# Generated by Django 5.2.10 on 2026-02-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_newsletter_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "janua_user_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("bookmarks", models.JSONField(default=list)),
                ("recently_viewed", models.JSONField(default=list)),
                (
                    "preferences",
                    models.JSONField(
                        default=dict,
                        help_text="User preferences: font_size, language, theme, etc.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("janua_user_id", models.CharField(db_index=True, max_length=255)),
                ("law_id", models.CharField(db_index=True, max_length=200)),
                ("article_id", models.CharField(db_index=True, max_length=100)),
                ("text", models.TextField()),
                ("highlight_start", models.IntegerField(blank=True, null=True)),
                ("highlight_end", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(default="yellow", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["janua_user_id", "law_id"],
                        name="api_annotat_janua_u_8cea73_idx",
                    ),
                    models.Index(
                        fields=["law_id", "article_id"],
                        name="api_annotat_law_id_0a427e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("janua_user_id", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("link", models.CharField(blank=True, default="", max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["janua_user_id", "is_read", "created_at"],
                        name="api_notific_janua_u_a2037e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("janua_user_id", models.CharField(db_index=True, max_length=255)),
                ("law_id", models.CharField(blank=True, default="", max_length=200)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                (
                    "alert_type",
                    models.CharField(
                        help_text="law_updated, new_version, new_law", max_length=20
                    ),
                ),
                ("delivery", models.CharField(default="in_app", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["janua_user_id", "is_active"],
                        name="api_userale_janua_u_913b8e_idx",
                    )
                ],
            },
        ),
    ]
