# Generated by Django 5.2.10 on 2026-03-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_judicialrecord"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contribution",
            new_name="api_contrib_status_b60291_idx",
            old_name="api_contribut_status_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="judicialrecord",
            new_name="api_judicia_tipo_a12939_idx",
            old_name="api_judicial_tipo_ma_idx",
        ),
        migrations.RenameIndex(
            model_name="judicialrecord",
            new_name="api_judicia_epoca_f9249a_idx",
            old_name="api_judicial_epoca_i_idx",
        ),
        migrations.AlterField(
            model_name="apikey",
            name="tier",
            field=models.CharField(
                choices=[
                    ("internal", "Internal (MADFAM)"),
                    ("free", "Free"),
                    ("community", "Community"),
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                ],
                db_index=True,
                default="free",
                max_length=20,
            ),
        ),
    ]
