# Generated by Django 5.2.10 on 2026-03-13 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_normalize_tier_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="rate_limit_per_hour",
            field=models.IntegerField(
                blank=True,
                help_text="Override tier default rate limit (1–100,000)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
    ]
