# Generated by Django 5.2.12 on 2026-03-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_add_free_member_tier_and_trial_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="law",
            name="name",
            field=models.CharField(help_text="Full name of the law", max_length=2000),
        ),
    ]
