# Generated by Django 5.2.12 on 2026-03-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_increase_law_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawversion",
            name="quality_grade",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("F", "F")],
                db_index=True,
                help_text="Parser quality grade. D/F are quarantined.",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lawversion",
            name="quality_score",
            field=models.FloatField(
                blank=True, help_text="Overall quality score 0-100.", null=True
            ),
        ),
    ]
