# Generated by Django 5.2.12 on 2026-03-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_add_quality_fields_to_law_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhooksubscription",
            name="law_id_filter",
            field=models.JSONField(
                default=list,
                help_text='e.g. ["cff", "lisr"] — empty list means all laws',
            ),
        ),
    ]
