# Generated by Django 5.2.12 on 2026-03-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_add_law_id_filter_to_webhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="law",
            name="domains",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Legal branches: ["labor", "fiscal", "criminal", ...]',
            ),
        ),
    ]
