# Generated by Django 5.2.12 on 2026-03-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_add_domains_to_law"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "feature_key",
                    models.CharField(
                        db_index=True,
                        help_text="latex_export, docx_export, epub_export, webhooks, graph_api, bulk_download, search_analytics, advanced_search",
                        max_length=50,
                    ),
                ),
                (
                    "use_case",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="research, work, personal, government, education",
                        max_length=50,
                    ),
                ),
                (
                    "janua_user_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "source_page",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="export_dropdown, pricing, search, graph",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["feature_key", "created_at"],
                        name="api_feature_feature_fa3f97_idx",
                    ),
                    models.Index(
                        fields=["email", "feature_key"],
                        name="api_feature_email_4b461d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email", "feature_key"),
                        name="unique_email_feature_interest",
                    )
                ],
            },
        ),
    ]
