# Generated by Django 5.2.12 on 2026-03-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_featureinterest"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureinterest",
            name="wishlist",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Free-text: what the user needs for full adoption",
            ),
        ),
    ]
