# Generated by Django 5.2.12 on 2026-04-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_featureinterest_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawversion",
            name="amendment_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tags for regulatory categorization, e.g. ['digital_services', 'cff_30b'].",
            ),
        ),
        migrations.AddField(
            model_name="lawversion",
            name="amendment_year",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Year of the amendment (extracted from publication_date).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="featureinterest",
            name="feature_key",
            field=models.CharField(
                db_index=True,
                help_text="latex_export, docx_export, epub_export, webhooks, graph_api, bulk_download, search_analytics, advanced_search, platform_access, early_access",
                max_length=50,
            ),
        ),
    ]
