# Generated by Django 5.2.16 on 2026-08-22 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_lawversion_amendment_tags_lawversion_amendment_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("isr_monthly", "ISR retención mensual (LISR 96)"),
                            ("isr_annual", "ISR tarifa anual (LISR 152)"),
                            ("subsidio_monthly", "Subsidio al empleo mensual"),
                            ("imss_rates", "Cuotas obrero-patronales IMSS"),
                            ("isn_rates", "Impuesto sobre nóminas por entidad"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                (
                    "period",
                    models.CharField(
                        default="monthly",
                        help_text='Bracket period: "monthly", "annual", "daily", or "n/a"',
                        max_length=20,
                    ),
                ),
                (
                    "rows",
                    models.JSONField(
                        default=list,
                        help_text="The table as published. For ISR/subsidio: a list of bracket objects. For imss_rates/isn_rates: a list of rate objects.",
                    ),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "LISR Art. 96"',
                        max_length=200,
                    ),
                ),
                ("vigencia_from", models.DateField(db_index=True)),
                ("vigencia_to", models.DateField(blank=True, db_index=True, null=True)),
                ("source_citation", models.TextField(blank=True, default="")),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                ("dof_date", models.DateField(blank=True, null=True)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("published", "Published (DOF-verified)"),
                            ("seed-unverified", "Seed (unverified)"),
                            ("operator", "Operator-entered"),
                        ],
                        db_index=True,
                        default="seed-unverified",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "fiscal table",
                "verbose_name_plural": "fiscal tables",
                "ordering": ["-year", "kind"],
                "indexes": [
                    models.Index(
                        fields=["kind", "year"], name="api_fiscalt_kind_24777a_idx"
                    ),
                    models.Index(
                        fields=["vigencia_from", "vigencia_to"],
                        name="api_fiscalt_vigenci_3aa66a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "year", "vigencia_from"),
                        name="uniq_fiscaltable_kind_year_vigencia",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MinimumWage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="The value in force, in MXN unless the unit says otherwise",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="MXN",
                        help_text='e.g. "MXN", "MXN/day", "percent"',
                        max_length=32,
                    ),
                ),
                (
                    "vigencia_from",
                    models.DateField(
                        db_index=True,
                        help_text="First day this value is in force (inclusive)",
                    ),
                ),
                (
                    "vigencia_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Last day in force (inclusive). NULL = still in force.",
                        null=True,
                    ),
                ),
                (
                    "source_citation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable citation, e.g. 'DOF 09-01-2026, CONASAMI'",
                    ),
                ),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "dof_date",
                    models.DateField(
                        blank=True,
                        help_text="Publication date in the Diario Oficial de la Federación",
                        null=True,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("published", "Published (DOF-verified)"),
                            ("seed-unverified", "Seed (unverified)"),
                            ("operator", "Operator-entered"),
                        ],
                        db_index=True,
                        default="seed-unverified",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("year", models.IntegerField(db_index=True)),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("general", "General (resto del país)"),
                            ("zlfn", "Zona Libre de la Frontera Norte"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "minimum wage",
                "verbose_name_plural": "minimum wages",
                "ordering": ["-vigencia_from", "zone"],
                "indexes": [
                    models.Index(
                        fields=["year", "zone"], name="api_minimum_year_01d83b_idx"
                    ),
                    models.Index(
                        fields=["vigencia_from", "vigencia_to"],
                        name="api_minimum_vigenci_5185c3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "zone", "vigencia_from"),
                        name="uniq_minwage_year_zone_vigencia",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UMAValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="The value in force, in MXN unless the unit says otherwise",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="MXN",
                        help_text='e.g. "MXN", "MXN/day", "percent"',
                        max_length=32,
                    ),
                ),
                (
                    "vigencia_from",
                    models.DateField(
                        db_index=True,
                        help_text="First day this value is in force (inclusive)",
                    ),
                ),
                (
                    "vigencia_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Last day in force (inclusive). NULL = still in force.",
                        null=True,
                    ),
                ),
                (
                    "source_citation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable citation, e.g. 'DOF 09-01-2026, CONASAMI'",
                    ),
                ),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "dof_date",
                    models.DateField(
                        blank=True,
                        help_text="Publication date in the Diario Oficial de la Federación",
                        null=True,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("published", "Published (DOF-verified)"),
                            ("seed-unverified", "Seed (unverified)"),
                            ("operator", "Operator-entered"),
                        ],
                        db_index=True,
                        default="seed-unverified",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "year",
                    models.IntegerField(
                        db_index=True, help_text="Fiscal year, e.g. 2026"
                    ),
                ),
                (
                    "monthly_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Monthly UMA as published (not daily x 30.4)",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "annual_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Annual UMA as published (not monthly x 12)",
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "verbose_name": "UMA value",
                "verbose_name_plural": "UMA values",
                "ordering": ["-vigencia_from"],
                "indexes": [
                    models.Index(fields=["year"], name="api_umavalu_year_1c631b_idx"),
                    models.Index(
                        fields=["vigencia_from", "vigencia_to"],
                        name="api_umavalu_vigenci_77acb0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "vigencia_from"), name="uniq_uma_year_vigencia"
                    )
                ],
            },
        ),
    ]
