# Generated by Django 5.2.17 on 2026-08-24 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_fiscal_values_feed"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDeCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="The value in force, in MXN unless the unit says otherwise",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="MXN",
                        help_text='e.g. "MXN", "MXN/day", "percent"',
                        max_length=32,
                    ),
                ),
                (
                    "vigencia_from",
                    models.DateField(
                        db_index=True,
                        help_text="First day this value is in force (inclusive)",
                    ),
                ),
                (
                    "vigencia_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Last day in force (inclusive). NULL = still in force.",
                        null=True,
                    ),
                ),
                (
                    "source_citation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable citation, e.g. 'DOF 09-01-2026, CONASAMI'",
                    ),
                ),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "dof_date",
                    models.DateField(
                        blank=True,
                        help_text="Publication date in the Diario Oficial de la Federación",
                        null=True,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("published", "Published (DOF-verified)"),
                            ("seed-unverified", "Seed (unverified)"),
                            ("operator", "Operator-entered"),
                        ],
                        db_index=True,
                        default="seed-unverified",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_currency",
                    models.CharField(
                        db_index=True,
                        default="USD",
                        help_text="ISO 4217 base currency (default USD — the only pair the DOF publishes daily)",
                        max_length=3,
                    ),
                ),
                (
                    "to_currency",
                    models.CharField(
                        db_index=True,
                        default="MXN",
                        help_text="ISO 4217 quote currency (default MXN)",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de cambio (DOF)",
                "verbose_name_plural": "tipos de cambio (DOF)",
                "ordering": ["-vigencia_from", "from_currency", "to_currency"],
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "vigencia_from"],
                        name="api_tipodec_from_cu_b3709f_idx",
                    ),
                    models.Index(
                        fields=["vigencia_from", "vigencia_to"],
                        name="api_tipodec_vigenci_c9e21f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_currency", "to_currency", "vigencia_from"),
                        name="uniq_tipocambio_pair_vigencia",
                    )
                ],
            },
        ),
    ]
