# Generated by Django 5.2.17 on 2026-09-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_tipo_de_cambio_feed"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscaltable",
            name="dof_codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="DOF nota_detalle 'codigo' of the publication carrying this table (e.g. '5777219' for the Anexo 8 de la RMF 2026). Empty when the table is not tied to a single DOF publication.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="minimumwage",
            name="dof_codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="DOF nota_detalle 'codigo' — the stable identifier of the exact publication, e.g. '5778072'. Together with dof_date it resolves to one document: https://dof.gob.mx/nota_detalle.php?codigo=<codigo>&fecha=<dd/mm/yyyy>. Empty when the row is not tied to a single DOF publication.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tipodecambio",
            name="dof_codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="DOF nota_detalle 'codigo' — the stable identifier of the exact publication, e.g. '5778072'. Together with dof_date it resolves to one document: https://dof.gob.mx/nota_detalle.php?codigo=<codigo>&fecha=<dd/mm/yyyy>. Empty when the row is not tied to a single DOF publication.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="umavalue",
            name="dof_codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="DOF nota_detalle 'codigo' — the stable identifier of the exact publication, e.g. '5778072'. Together with dof_date it resolves to one document: https://dof.gob.mx/nota_detalle.php?codigo=<codigo>&fecha=<dd/mm/yyyy>. Empty when the row is not tied to a single DOF publication.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fiscaltable",
            name="kind",
            field=models.CharField(
                choices=[
                    ("isr_monthly", "ISR retención mensual (LISR 96)"),
                    ("isr_annual", "ISR tarifa anual (LISR 152)"),
                    ("subsidio_monthly", "Subsidio al empleo mensual"),
                    ("subsidio_rule", "Subsidio al empleo (regla derivada)"),
                    ("imss_rates", "Cuotas obrero-patronales IMSS"),
                    ("isn_rates", "Impuesto sobre nóminas por entidad"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
