# Generated by Django 5.2.17 on 2026-09-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_fiscal_dof_codigo_and_subsidio_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "official_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador de la ley en el corpus, p. ej. 'lft', 'lss', 'cff'",
                        max_length=200,
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        db_index=True,
                        help_text="Artículo normalizado: '59', '39-A', '1-A', '113-J', '5-A'",
                        max_length=32,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        db_index=True, help_text="Primer día en que rige (inclusive)"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Último día en que rige (inclusive). NULL = sigue vigente.",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Emisor de la lectura primaria, p. ej. 'Cámara de Diputados, LeyesBiblio', 'DOF', 'STPS', 'SAT'",
                        max_length=200,
                    ),
                ),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "dof_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de la publicación en el DOF que fija este texto o valor",
                        null=True,
                    ),
                ),
                (
                    "dof_codigo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="'codigo' de nota_detalle del DOF, p. ej. '5786537' para el decreto de reducción de la jornada laboral. Con dof_date resuelve a un documento único.",
                        max_length=20,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("published", "Published (DOF-verified)"),
                            ("seed-unverified", "Seed (unverified)"),
                            ("operator", "Operator-entered"),
                        ],
                        db_index=True,
                        default="seed-unverified",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "imss_alta_ventana_dias_habiles",
                                "Ventana para el alta en el IMSS (días hábiles)",
                            ),
                            (
                                "contrato_escrito_desde_inicio",
                                "Contrato escrito desde el inicio",
                            ),
                            ("prueba_dias_max", "Periodo de prueba (días máximo)"),
                            (
                                "prueba_dias_max_direccion",
                                "Periodo de prueba, puestos de dirección (días máximo)",
                            ),
                            (
                                "capacitacion_inicial_meses_max",
                                "Capacitación inicial (meses máximo)",
                            ),
                            (
                                "capacitacion_inicial_meses_max_direccion",
                                "Capacitación inicial, puestos de dirección (meses máximo)",
                            ),
                            (
                                "jornada_semanal_horas_max",
                                "Jornada ordinaria semanal (horas máximo)",
                            ),
                            (
                                "jornada_diurna_horas_max",
                                "Jornada diurna diaria (horas máximo)",
                            ),
                            (
                                "jornada_nocturna_horas_max",
                                "Jornada nocturna diaria (horas máximo)",
                            ),
                            (
                                "jornada_mixta_horas_max",
                                "Jornada mixta diaria (horas máximo)",
                            ),
                            (
                                "tiempo_extra_semanal_horas_max",
                                "Tiempo extraordinario semanal (horas máximo)",
                            ),
                            (
                                "semana_reducida_prorrateo",
                                "Cotización con jornada o semana reducida",
                            ),
                            (
                                "ptu_eventuales_dias_min",
                                "PTU de eventuales (días mínimo trabajados)",
                            ),
                            (
                                "ptu_fecha_limite_dias",
                                "PTU: días para repartir tras la declaración anual",
                            ),
                            ("aguinaldo_dias_min", "Aguinaldo (días mínimo)"),
                            ("aguinaldo_fecha_limite", "Aguinaldo: fecha límite"),
                            (
                                "vacaciones_dias_por_anio",
                                "Vacaciones por año de servicio (tabla)",
                            ),
                            (
                                "prima_vacacional_pct_min",
                                "Prima vacacional (porcentaje mínimo)",
                            ),
                            (
                                "retencion_isr_honorarios_pct",
                                "Retención de ISR sobre honorarios (porcentaje)",
                            ),
                            (
                                "retencion_iva_honorarios_fraccion",
                                "Retención de IVA sobre honorarios (fracción del trasladado)",
                            ),
                            ("resico_tope_anual", "Tope anual de ingresos RESICO"),
                            (
                                "recargos_tasa_mensual",
                                "Tasa mensual de recargos por mora",
                            ),
                            (
                                "actualizacion_factor",
                                "Factor de actualización (CFF 17-A)",
                            ),
                            (
                                "repse_obligatorio_condiciones",
                                "REPSE: condiciones que lo hacen obligatorio",
                            ),
                            ("repse_vigencia_anios", "REPSE: vigencia del registro"),
                            (
                                "teletrabajo_umbral_pct",
                                "Teletrabajo: umbral del tiempo en domicilio",
                            ),
                            (
                                "nom035_umbral_personas",
                                "NOM-035: obligaciones por tamaño del centro de trabajo",
                            ),
                            (
                                "recaracterizacion_indicios",
                                "Indicios de relación laboral (LFT 20)",
                            ),
                            ("sat_catalogo", "Catálogo del SAT para el CFDI 4.0"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="El valor de la regla: número, cadena, lista o tabla. La forma por kind se documenta en docs/labor/README.md."
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='p. ej. "dias_habiles", "horas/semana", "percent", "MXN", "tabla"',
                        max_length=40,
                    ),
                ),
                (
                    "payer_legal_form",
                    models.CharField(
                        choices=[
                            ("any", "Cualquiera"),
                            ("persona_moral", "Persona moral"),
                            ("persona_fisica", "Persona física"),
                        ],
                        db_index=True,
                        default="any",
                        help_text="Forma legal del pagador cuando la regla depende de ella",
                        max_length=20,
                    ),
                ),
                (
                    "provider_regime",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Régimen fiscal del prestador cuando la regla depende de él, con la clave del c_RegimenFiscal del SAT: '612', '626', '601'. Vacío = la regla no distingue.",
                        max_length=20,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tipo de servicio cuando la regla depende de él, p. ej. 'servicios_profesionales', 'autotransporte_terrestre_bienes'. Vacío = la regla no distingue.",
                        max_length=60,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Etiqueta legible para una interfaz, en español",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "regla laboral",
                "verbose_name_plural": "reglas laborales",
                "ordering": ["kind", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["kind", "effective_from"],
                        name="api_laborru_kind_593964_idx",
                    ),
                    models.Index(
                        fields=["kind", "payer_legal_form", "provider_regime"],
                        name="api_laborru_kind_a704a2_idx",
                    ),
                    models.Index(
                        fields=["effective_from", "effective_to"],
                        name="api_laborru_effecti_e76c33_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "kind",
                            "payer_legal_form",
                            "provider_regime",
                            "service",
                            "effective_from",
                        ),
                        name="uniq_laborrule_kind_dims_vigencia",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LawArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "official_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador de la ley en el corpus, p. ej. 'lft', 'lss', 'cff'",
                        max_length=200,
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        db_index=True,
                        help_text="Artículo normalizado: '59', '39-A', '1-A', '113-J', '5-A'",
                        max_length=32,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        db_index=True, help_text="Primer día en que rige (inclusive)"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Último día en que rige (inclusive). NULL = sigue vigente.",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Emisor de la lectura primaria, p. ej. 'Cámara de Diputados, LeyesBiblio', 'DOF', 'STPS', 'SAT'",
                        max_length=200,
                    ),
                ),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "dof_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de la publicación en el DOF que fija este texto o valor",
                        null=True,
                    ),
                ),
                (
                    "dof_codigo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="'codigo' de nota_detalle del DOF, p. ej. '5786537' para el decreto de reducción de la jornada laboral. Con dof_date resuelve a un documento único.",
                        max_length=20,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("published", "Published (DOF-verified)"),
                            ("seed-unverified", "Seed (unverified)"),
                            ("operator", "Operator-entered"),
                        ],
                        db_index=True,
                        default="seed-unverified",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "text",
                    models.TextField(
                        help_text="Texto íntegro del artículo, tal como se publica"
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Edición del texto vigente de la que se transcribió, p. ej. 'Última reforma DOF 14-05-2026'",
                        max_length=120,
                    ),
                ),
                (
                    "derogado",
                    models.BooleanField(
                        default=False,
                        help_text="El artículo dice 'Se deroga'. Se publica igual —un consumidor necesita saber que su base legal desapareció, no un 404.",
                    ),
                ),
                (
                    "reformas_dof",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Fechas DOF (dd-mm-aaaa) de las reformas que la Cámara imprime bajo el artículo, de la más antigua a la más reciente.",
                    ),
                ),
            ],
            options={
                "verbose_name": "artículo de ley (con vigencia)",
                "verbose_name_plural": "artículos de ley (con vigencia)",
                "ordering": ["official_id", "article", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["official_id", "article", "effective_from"],
                        name="api_lawarti_officia_c2c280_idx",
                    ),
                    models.Index(
                        fields=["effective_from", "effective_to"],
                        name="api_lawarti_effecti_fdc2ff_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("official_id", "article", "effective_from"),
                        name="uniq_lawarticle_ley_articulo_vigencia",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SatCatalogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "official_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador de la ley en el corpus, p. ej. 'lft', 'lss', 'cff'",
                        max_length=200,
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        db_index=True,
                        help_text="Artículo normalizado: '59', '39-A', '1-A', '113-J', '5-A'",
                        max_length=32,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        db_index=True, help_text="Primer día en que rige (inclusive)"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Último día en que rige (inclusive). NULL = sigue vigente.",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Emisor de la lectura primaria, p. ej. 'Cámara de Diputados, LeyesBiblio', 'DOF', 'STPS', 'SAT'",
                        max_length=200,
                    ),
                ),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "dof_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de la publicación en el DOF que fija este texto o valor",
                        null=True,
                    ),
                ),
                (
                    "dof_codigo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="'codigo' de nota_detalle del DOF, p. ej. '5786537' para el decreto de reducción de la jornada laboral. Con dof_date resuelve a un documento único.",
                        max_length=20,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("published", "Published (DOF-verified)"),
                            ("seed-unverified", "Seed (unverified)"),
                            ("operator", "Operator-entered"),
                        ],
                        db_index=True,
                        default="seed-unverified",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "catalog",
                    models.CharField(
                        choices=[
                            ("c_RegimenFiscal", "c_RegimenFiscal"),
                            ("c_TipoRegimen", "c_TipoRegimen"),
                            ("c_TipoContrato", "c_TipoContrato"),
                            ("c_TipoJornada", "c_TipoJornada"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, help_text="Clave, p. ej. '605'", max_length=10
                    ),
                ),
                (
                    "label",
                    models.TextField(
                        help_text="Descripción tal como la publica el SAT"
                    ),
                ),
                (
                    "aplica_fisica",
                    models.BooleanField(
                        blank=True,
                        help_text="Sólo c_RegimenFiscal: la clave aplica a personas físicas",
                        null=True,
                    ),
                ),
                (
                    "aplica_moral",
                    models.BooleanField(
                        blank=True,
                        help_text="Sólo c_RegimenFiscal: la clave aplica a personas morales",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "clave de catálogo SAT",
                "verbose_name_plural": "claves de catálogos SAT",
                "ordering": ["catalog", "code", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["catalog", "code", "effective_from"],
                        name="api_satcata_catalog_a7b88d_idx",
                    ),
                    models.Index(
                        fields=["effective_from", "effective_to"],
                        name="api_satcata_effecti_a9ca65_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("catalog", "code", "effective_from"),
                        name="uniq_satcatalogo_catalogo_clave_vigencia",
                    )
                ],
            },
        ),
    ]
