# Generated by Django 5.2.17 on 2026-09-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_labor_article_cabe_la_cita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laborrule",
            name="kind",
            field=models.CharField(
                choices=[
                    (
                        "imss_alta_ventana_dias_habiles",
                        "Ventana para el alta en el IMSS (días hábiles)",
                    ),
                    (
                        "contrato_escrito_desde_inicio",
                        "Contrato escrito desde el inicio",
                    ),
                    ("prueba_dias_max", "Periodo de prueba (días máximo)"),
                    (
                        "prueba_dias_max_direccion",
                        "Periodo de prueba, puestos de dirección (días máximo)",
                    ),
                    (
                        "capacitacion_inicial_meses_max",
                        "Capacitación inicial (meses máximo)",
                    ),
                    (
                        "capacitacion_inicial_meses_max_direccion",
                        "Capacitación inicial, puestos de dirección (meses máximo)",
                    ),
                    (
                        "jornada_semanal_horas_max",
                        "Jornada ordinaria semanal (horas máximo)",
                    ),
                    (
                        "jornada_diurna_horas_max",
                        "Jornada diurna diaria (horas máximo)",
                    ),
                    (
                        "jornada_nocturna_horas_max",
                        "Jornada nocturna diaria (horas máximo)",
                    ),
                    ("jornada_mixta_horas_max", "Jornada mixta diaria (horas máximo)"),
                    (
                        "tiempo_extra_semanal_horas_max",
                        "Tiempo extraordinario semanal (horas máximo)",
                    ),
                    (
                        "semana_reducida_prorrateo",
                        "Cotización con jornada o semana reducida",
                    ),
                    (
                        "ptu_eventuales_dias_min",
                        "PTU de eventuales (días mínimo trabajados)",
                    ),
                    (
                        "ptu_fecha_limite_dias",
                        "PTU: días para repartir tras la declaración anual",
                    ),
                    ("aguinaldo_dias_min", "Aguinaldo (días mínimo)"),
                    ("aguinaldo_fecha_limite", "Aguinaldo: fecha límite"),
                    (
                        "vacaciones_dias_por_anio",
                        "Vacaciones por año de servicio (tabla)",
                    ),
                    (
                        "prima_vacacional_pct_min",
                        "Prima vacacional (porcentaje mínimo)",
                    ),
                    (
                        "retencion_isr_honorarios_pct",
                        "Retención de ISR sobre honorarios (porcentaje)",
                    ),
                    (
                        "retencion_iva_honorarios_fraccion",
                        "Retención de IVA sobre honorarios (fracción del trasladado)",
                    ),
                    ("resico_tope_anual", "Tope anual de ingresos RESICO"),
                    ("recargos_tasa_mensual", "Tasa mensual de recargos por mora"),
                    ("actualizacion_factor", "Factor de actualización (CFF 17-A)"),
                    (
                        "repse_obligatorio_condiciones",
                        "REPSE: condiciones que lo hacen obligatorio",
                    ),
                    ("repse_vigencia_anios", "REPSE: vigencia del registro"),
                    (
                        "teletrabajo_umbral_pct",
                        "Teletrabajo: umbral del tiempo en domicilio",
                    ),
                    (
                        "nom035_umbral_personas",
                        "NOM-035: obligaciones por tamaño del centro de trabajo",
                    ),
                    (
                        "nom037_aplicabilidad",
                        "NOM-037: cuándo aplica la norma de teletrabajo",
                    ),
                    (
                        "relacion_trabajo_elementos",
                        "Elementos de la relación de trabajo (LFT 20)",
                    ),
                    (
                        "recaracterizacion_indicios",
                        "Indicios de relación laboral (orientativos, no de ley)",
                    ),
                    ("sat_catalogo", "Catálogo del SAT para el CFDI 4.0"),
                    (
                        "opinion_32d_vigencia_dias",
                        "Opinión del cumplimiento (32-D): vigencia en días",
                    ),
                    (
                        "cfdi_nomina_por_periodo",
                        "CFDI de nómina: cuándo debe expedirse",
                    ),
                    (
                        "comisiones_mixtas_umbral_personas",
                        "Comisiones mixtas de capacitación: umbral de personas",
                    ),
                    (
                        "jcf_validacion_periodicidad_dias",
                        "Jóvenes Construyendo el Futuro: periodicidad de la validación",
                    ),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
