# Generated by Django 5.2.10 on 2026-02-06 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("scraper", "Automated Scraper"),
                            ("api", "API Endpoint"),
                            ("manual", "Manual Download"),
                            ("foia", "FOIA/Transparency Request"),
                            ("partnership", "Institutional Partnership"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("federal", "Federal"),
                            ("state", "State"),
                            ("municipal", "Municipal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_url", models.URLField(blank=True, max_length=500)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("municipality", models.CharField(blank=True, max_length=100)),
                ("last_check", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("down", "Down"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "scraper_class",
                    models.CharField(
                        blank=True,
                        help_text="Python dotted path to scraper class",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["level", "state", "name"],
            },
        ),
        migrations.CreateModel(
            name="AcquisitionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(max_length=200)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("found", models.IntegerField(default=0)),
                ("downloaded", models.IntegerField(default=0)),
                ("failed", models.IntegerField(default=0)),
                ("ingested", models.IntegerField(default=0)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("error_summary", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="dataops.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GapRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("federal", "Federal"),
                            ("state", "State"),
                            ("municipal", "Municipal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("municipality", models.CharField(blank=True, max_length=100)),
                ("law_name", models.CharField(blank=True, max_length=500)),
                ("ojn_file_id", models.CharField(blank=True, max_length=100)),
                (
                    "gap_type",
                    models.CharField(
                        choices=[
                            ("dead_link", "Dead Link (404/410)"),
                            ("missing_source", "No Scraper/Source Exists"),
                            ("low_count", "Suspiciously Low Count"),
                            ("not_scraped", "Source Known but Not Yet Scraped"),
                            ("parse_failure", "Downloaded but Failed to Parse"),
                            ("site_redesign", "Source Site Changed Structure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("resolved", "Resolved"),
                            ("permanent", "Permanent Gap"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "current_tier",
                    models.IntegerField(
                        choices=[
                            (0, "Tier 0: Automated Scraping"),
                            (1, "Tier 1: Web Search + Alt Source"),
                            (2, "Tier 2: Direct Contact"),
                            (3, "Tier 3: FOIA/Transparency"),
                            (4, "Tier 4: Institutional Partnership"),
                        ],
                        default=0,
                    ),
                ),
                ("attempts", models.JSONField(blank=True, default=list)),
                ("next_action", models.CharField(blank=True, max_length=500)),
                ("next_action_date", models.DateField(blank=True, null=True)),
                ("resolved_via", models.CharField(blank=True, max_length=200)),
                ("resolved_url", models.URLField(blank=True, max_length=500)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gaps",
                        to="dataops.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "current_tier", "state"],
                "indexes": [
                    models.Index(
                        fields=["status", "current_tier"],
                        name="dataops_gap_status_45214a_idx",
                    ),
                    models.Index(
                        fields=["level", "state"], name="dataops_gap_level_c477d7_idx"
                    ),
                    models.Index(
                        fields=["gap_type"], name="dataops_gap_gap_typ_edd923_idx"
                    ),
                ],
            },
        ),
    ]
