"""Transitorio ids never overwrite substantive articles (#218, #222).

Covers ``apps.api.transitorios`` directly and through
``index_laws.Command.extract_articles_from_xml``:

* the LEGACY XML shape still live in production for LFPDPPP (generated by the
  pre-#218 parser): transitorios serialised as ``<num>Artículo N</num>`` nodes
  whose text opens with the ordinal heading ("Octavo.- …"), plus a second
  transitorios block from the DOF 14-11-2025 reform decree. Production served
  these as ``1-dup1``, ``10-dup1`` … ``10-dup11`` (109 entries);
* the CURRENT parser shape (``trans-N`` / ``trans-rK-N`` node ids), including
  an end-to-end parse → XML → index-extraction round trip.
"""

from unittest.mock import MagicMock

import pytest

from apps.api.transitorios import (
    article_kind,
    resolve_article_ids,
    split_ordinal_heading,
    transitorio_id,
)
from tests.pipeline.test_index_laws import Command

AKN = "http://docs.oasis-open.org/legaldocml/ns/akn/3.0"


def _art(node_id, num, text):
    return (
        f'<article id="{node_id}"><num>{num}</num>'
        f"<content><p>{text}</p></content></article>"
    )


# Mirrors the production LFPDPPP document order: body articles, then the
# legacy ordinal-headed nodes (decree block, then the 2025-11-14 reform block,
# with a PDF line-wrap split inside "Décimo Quinto"), then the proper
# trans-N nodes that duplicate the first block.
LEGACY_LFPDPPP_XML = (
    f'<?xml version="1.0" encoding="UTF-8"?><akomaNtoso xmlns="{AKN}"><act><body>'
    + _art("art-1", "Artículo 1", "La presente Ley es de orden público.")
    + _art("art-2", "Artículo 2", "Para los efectos de esta Ley, se entenderá por:")
    + _art(
        "art-8",
        "Artículo 8",
        "Tratándose de datos personales sensibles, el responsable deberá "
        "obtener el consentimiento expreso y por escrito del titular.",
    )
    + _art(
        "art-9",
        "Artículo 9",
        "El responsable no estará obligado a recabar el consentimiento.",
    )
    + _art("art-10", "Artículo 10", "Principio de calidad de los datos.")
    + _art(
        "art-20", "Artículo 20", "El responsable o tercero deberá establecer controles."
    )
    + _art(
        "art-1",
        "Artículo 1",
        "Primero.- El presente Decreto entrará en vigor al día siguiente de su "
        "publicación en el Diario Oficial de la Federación.",
    )
    + _art("art-2", "Artículo 2", "Segundo.- Se abroga la Ley Federal de 2010.")
    + _art(
        "art-8",
        "Artículo 8",
        "Octavo.- Los registros, padrones y sistemas que integran la Plataforma "
        "Nacional de Transparencia.",
    )
    + _art(
        "art-10",
        "Artículo 10",
        "Décimo.- Los procedimientos iniciados con anterioridad.",
    )
    + _art("art-10", "Artículo 10", "Décimo Primero.- Los municipios podrán cumplir.")
    + _art(
        "art-10",
        "Artículo 10",
        "Décimo Quinto.- Para efectos de lo dispuesto en los transitorios "
        "Quinto, Sexto, Séptimo, Octavo y",
    )
    + _art(
        "art-10",
        "Artículo 10",
        "Décimo Tercero del presente Decreto el Pleno del Instituto deberá.",
    )
    + _art(
        "art-20",
        "Artículo 20",
        "Vigésimo.- El Poder Judicial deberá habilitar juzgados.",
    )
    + _art(
        "art-1",
        "Artículo 1",
        "Primero. El presente Decreto entrará en vigor el día siguiente al de su "
        "publicación.",
    )
    + _art(
        "art-2",
        "Artículo 2",
        "Segundo. La aplicación de lo dispuesto en el presente Decreto.",
    )
    + _art(
        "trans-1",
        "Primero",
        "El presente Decreto entrará en vigor al día siguiente de su publicación "
        "en el Diario Oficial de la Federación.",
    )
    + _art(
        "trans-8",
        "Octavo",
        "Los registros, padrones y sistemas que integran la Plataforma Nacional "
        "de Transparencia.",
    )
    + "</body></act></akomaNtoso>"
)


@pytest.fixture
def command():
    cmd = Command()
    cmd.stdout = MagicMock()
    cmd.stderr = MagicMock()
    cmd.style = MagicMock()
    return cmd


class TestLegacyLfpdpppXml:
    @pytest.fixture
    def by_id(self, command):
        articles = command.extract_articles_from_xml(LEGACY_LFPDPPP_XML, "lfpdppp")
        ids = [a["article_id"] for a in articles]
        assert len(ids) == len(set(ids)), f"duplicate ids: {ids}"
        return {a["article_id"]: a for a in articles}

    def test_exact_id_set(self, by_id):
        assert set(by_id) == {
            "1",
            "2",
            "8",
            "9",
            "10",
            "20",
            "T-1",
            "T-2",
            "T-8",
            "T-10",
            "T-11",
            "T-15",
            "T-20",
            "T-R2-1",
            "T-R2-2",
        }

    def test_substantive_articles_keep_their_ids_and_text(self, by_id):
        assert "expreso y por escrito" in by_id["8"]["text"]
        assert "no estará obligado a recabar" in by_id["9"]["text"]
        assert by_id["2"]["text"].startswith("Para los efectos de esta Ley")
        for aid in ("1", "2", "8", "9", "10", "20"):
            assert by_id[aid]["is_transitorio"] is False

    def test_no_dup_suffixes(self, by_id):
        assert not [aid for aid in by_id if "dup" in aid]

    def test_transitorios_renumbered_from_heading(self, by_id):
        assert by_id["T-8"]["text"].startswith("Los registros, padrones")
        assert by_id["T-11"]["text"].startswith("Los municipios")
        assert by_id["T-20"]["text"].startswith("El Poder Judicial")
        assert all(by_id[a]["is_transitorio"] for a in by_id if a.startswith("T-"))

    def test_wrapped_line_fragment_is_merged(self, by_id):
        text = by_id["T-15"]["text"]
        assert "Octavo y" in text
        assert "Décimo Tercero del presente Decreto el Pleno" in text

    def test_reform_decree_is_second_block(self, by_id):
        assert by_id["T-R2-1"]["text"].startswith(
            "El presente Decreto entrará en vigor el día siguiente al de su"
        )
        assert by_id["T-R2-2"]["text"].startswith("La aplicación")
        # The first decree's Primero is untouched by the reform block.
        assert "Diario Oficial" in by_id["T-1"]["text"]


class TestCurrentParserShape:
    def test_reform_block_node_ids(self, command):
        xml = (
            f'<?xml version="1.0" encoding="UTF-8"?><akomaNtoso xmlns="{AKN}">'
            "<act><body>"
            + _art("art-1", "Artículo 1", "Objeto de la ley.")
            + _art("trans-1", "PRIMERO", "Entra en vigor.")
            + _art("trans-r2-1", "Primero", "El decreto de reforma entra en vigor.")
            + _art("trans-r2-2", "Segundo", "Se derogan las disposiciones.")
            + "</body></act></akomaNtoso>"
        )
        ids = [a["article_id"] for a in command.extract_articles_from_xml(xml, "x")]
        assert ids == ["1", "T-1", "T-R2-1", "T-R2-2"]

    def test_parse_then_index_round_trip(self, command, tmp_path):
        from apps.parsers.akn_generator_v2 import AkomaNtosoGeneratorV2

        text = (
            "Artículo 1.- La presente Ley es de orden público.\n"
            "Artículo 8.- Tratándose de datos personales sensibles, el "
            "responsable deberá obtener el consentimiento expreso y por escrito.\n"
            "TRANSITORIOS\n"
            "PRIMERO.- El presente Decreto entrará en vigor al día siguiente.\n"
            "OCTAVO.- Los registros de la Plataforma Nacional de Transparencia.\n"
            "DECRETO por el que se reforma el artículo 8.\n"
            "Transitorios\n"
            "Primero. El presente Decreto entrará en vigor el día siguiente.\n"
        )
        generator = AkomaNtosoGeneratorV2()
        metadata = generator.create_frbr_metadata(
            "ley", "2025-03-20", "lfpdppp", "Ley de prueba"
        )
        xml_path = tmp_path / "law.xml"
        generator.generate_xml(text, metadata, xml_path)
        articles = command.extract_articles_from_xml(
            xml_path.read_text(encoding="utf-8"), "lfpdppp"
        )
        by_id = {a["article_id"]: a for a in articles}

        assert set(by_id) == {"1", "8", "T-1", "T-8", "T-R2-1"}
        assert "expreso y por escrito" in by_id["8"]["text"]
        assert "Plataforma Nacional" in by_id["T-8"]["text"]
        # The second TRANSITORIOS header closes block 1: the reform block's
        # heading and first provision never bleed into Octavo.
        assert "Transitorios" not in by_id["T-8"]["text"]
        assert "Primero. El presente" not in by_id["T-8"]["text"]


class TestHelpers:
    @pytest.mark.parametrize(
        "text,expected",
        [
            ("Octavo.- Los registros", (8, "Los registros")),
            ("Décimo Primero.- Los municipios", (11, "Los municipios")),
            ("PRIMERO. El presente", (1, "El presente")),
            ("Único.- Se reforma", (1, "Se reforma")),
            ("Décimo Tercero del presente Decreto", None),
            ("Para los efectos de esta Ley", None),
            ("", None),
        ],
    )
    def test_split_ordinal_heading(self, text, expected):
        assert split_ordinal_heading(text) == expected

    def test_transitorio_id(self):
        assert transitorio_id(8) == "T-8"
        assert transitorio_id(1, 1) == "T-1"
        assert transitorio_id(3, 2) == "T-R2-3"

    @pytest.mark.parametrize(
        "source,expected",
        [
            ({"article": "8", "is_transitorio": False}, "articulo"),
            ({"article": "T-8", "is_transitorio": True}, "transitorio"),
            ({"article": "T-R2-1"}, "transitorio"),
            ({"article": "8"}, "articulo"),
            ({"article": "Tercera"}, "articulo"),
        ],
    )
    def test_article_kind(self, source, expected):
        assert article_kind(source) == expected

    def test_ordinal_only_instruments_are_not_reinterpreted(self):
        """Without digit-numbered articles, ordinals ARE the numbering scheme:
        no content-based transitorio detection may fire."""
        articles = [
            {"article_id": "Primera", "is_transitorio": False, "text": "Objeto."},
            {"article_id": "Primera", "is_transitorio": False, "text": "Primero.- x"},
        ]
        out = resolve_article_ids(articles, has_numeric_articles=False)
        assert [a["article_id"] for a in out] == ["Primera", "Primera-dup1"]

    def test_unresolvable_collision_is_suffixed_and_reported(self):
        warnings = []
        articles = [
            {"article_id": "27", "is_transitorio": False, "text": "Notificaciones."},
            {"article_id": "27", "is_transitorio": False, "text": "artículo 27; …"},
        ]
        out = resolve_article_ids(articles, True, warn=warnings.append)
        assert [a["article_id"] for a in out] == ["27", "27-dup1"]
        assert warnings and "27-dup1" in warnings[0]

    def test_distinct_transitorios_with_same_id_are_both_kept(self):
        articles = [
            {
                "article_id": "T-9",
                "is_transitorio": True,
                "text": "Los procedimientos A.",
            },
            {
                "article_id": "T-9",
                "is_transitorio": True,
                "text": "Otra disposición B.",
            },
        ]
        out = resolve_article_ids(articles, True)
        assert [a["article_id"] for a in out] == ["T-9", "T-9-dup1"]
