apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tezca

resources:
- namespace.yaml
- tezca-api-deployment.yaml
- tezca-api-service.yaml
- tezca-web-deployment.yaml
- tezca-web-service.yaml
- tezca-admin-deployment.yaml
- tezca-admin-service.yaml
- tezca-worker-deployment.yaml
- tezca-beat-deployment.yaml
- tezca-redis-deployment.yaml
- tezca-redis-service.yaml
- tezca-redis-pvc.yaml
- tezca-es-deployment.yaml
- tezca-es-service.yaml
- tezca-es-pvc.yaml
- tezca-pdbs.yaml
- tezca-db-backup-cronjob.yaml
- network-policies.yaml
images:
- digest: sha256:7ea46029d9ff8689943d2409f447502e52cdc48fc1af96fa9576cc43f4dcbc31
  name: ghcr.io/madfam-org/tezca/admin
  newName: ghcr.io/madfam-org/tezca-admin
- digest: sha256:2ce8ac7176c96baed3a4f720c9bd29bab7021117d038e4ccffa3f0927e17f7c7
  name: ghcr.io/madfam-org/tezca/api
  newName: ghcr.io/madfam-org/tezca-api
- digest: sha256:5da1c6979734cf09c96ae93ad20645e26a7e2b1f316b46e3f7fd7e8556074f9d
  name: ghcr.io/madfam-org/tezca/web
  newName: ghcr.io/madfam-org/tezca-web
