apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tezca

resources:
- namespace.yaml
- tezca-api-deployment.yaml
- tezca-api-service.yaml
- tezca-web-deployment.yaml
- tezca-web-service.yaml
- tezca-admin-deployment.yaml
- tezca-admin-service.yaml
- tezca-worker-deployment.yaml
- tezca-beat-deployment.yaml
- tezca-redis-deployment.yaml
- tezca-redis-service.yaml
- tezca-redis-pvc.yaml
- tezca-es-deployment.yaml
- tezca-es-service.yaml
- tezca-es-pvc.yaml
- tezca-pdbs.yaml
images:
- digest: sha256:03cb7a16217bdd67121221036f422f059b1d345a9917890d5cba2698d796423f
  name: ghcr.io/madfam-org/tezca/admin
  newName: ghcr.io/madfam-org/tezca/admin
- digest: sha256:d8a9b6307e71c5c4caafb7e783d80d6d74e63366f0d6c00fc1724f38c4f8de97
  name: ghcr.io/madfam-org/tezca/api
  newName: ghcr.io/madfam-org/tezca/api
- digest: sha256:53ddb88aa03aa86465c0c1712a1ab969035421b9c1bcf0df0b44616e58302b86
  name: ghcr.io/madfam-org/tezca/web
  newName: ghcr.io/madfam-org/tezca/web
