apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tezca

resources:
- namespace.yaml
- tezca-api-deployment.yaml
- tezca-api-service.yaml
- tezca-web-deployment.yaml
- tezca-web-service.yaml
- tezca-admin-deployment.yaml
- tezca-admin-service.yaml
- tezca-worker-deployment.yaml
- tezca-beat-deployment.yaml
- tezca-redis-deployment.yaml
- tezca-redis-service.yaml
- tezca-redis-pvc.yaml
- tezca-es-deployment.yaml
- tezca-es-service.yaml
- tezca-es-pvc.yaml
- tezca-pdbs.yaml
- tezca-db-backup-cronjob.yaml
- network-policies.yaml
images:
- digest: sha256:37eb441c5c4e1467f6735213e4493f9431f5491e94e2fe45990a3989175e2277
  name: ghcr.io/madfam-org/tezca/admin
  newName: ghcr.io/madfam-org/tezca-admin
- digest: sha256:5f289e98fe5d53c3cf3a42cb9da10bb9a8f5ed64f1f8128ed67861e5f8a2fa67
  name: ghcr.io/madfam-org/tezca/api
  newName: ghcr.io/madfam-org/tezca-api
- digest: sha256:60a8cff8e7b2e1054b0a56c4883201f36599818100a9e8e442c4d9234f1541fe
  name: ghcr.io/madfam-org/tezca/web
  newName: ghcr.io/madfam-org/tezca-web
